---
strategy: polling
no_screen_padding: 
dark_mode: 
static_data: 
polling_verb: GET
polling_url: https://www.dn.se/rss/
polling_headers: 
polling_body: 
id: 176747
custom_fields:
- keyname: author_bio
  name: About This Plugin
  field_type: author_bio
  description: DN Latest News was created by Tim.
  github_url: https://github.com/tkilaker/trmnl-recipes
  email_address: tkilaker@icloud.com
name: DN Latest News
refresh_interval: 30
