---
title: Sydsvenskan Latest News
author: Tim Kil√•ker
category: news
icon: newspaper

strategy: polling
polling_verb: GET
polling_url: https://www.sydsvenskan.se/feeds/feed.xml

refresh_interval: 30

layouts:
  - full
